# Generated by Django 5.1.1 on 2024-09-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_province_island_supportgroup_contact_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.RemoveField(
            model_name='supportgroup',
            name='province',
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='city',
            field=models.CharField(choices=[('Far North', 'Far North District'), ('Whangarei', 'Whangarei District'), ('Kaipara', 'Kaipara District'), ('Auckland', 'Auckland'), ('Thames-Coromandel', 'Thames-Coromandel District'), ('Hauraki', 'Hauraki District'), ('Waikato', 'Waikato District'), ('Matamata-Piako', 'Matamata-Piako District'), ('Hamilton', 'Hamilton'), ('Waipa', 'Waipa District'), ('South Waikato', 'South Waikato District'), ('Otorohanga', 'Otorohanga District'), ('Waitomo', 'Waitomo District'), ('Taupo', 'Taupo District'), ('Western Bay of Plenty', 'Western Bay of Plenty District'), ('Tauranga', 'Tauranga'), ('Opotiki', 'Opotiki District'), ('Whakatane', 'Whakatane District'), ('Rotorua\t', 'Rotorua District'), ('Kawerau', 'Kawerau District'), ('Gisborne', 'Gisborne District'), ('Wairoa', 'Wairoa District'), ('Hastings', 'Hastings District'), ('Napier', 'Napier'), ("Central Hawke's Bay", "Central Hawke's Bay District"), ('New Plymouth', 'New Plymouth District'), ('Stratford', 'Stratford District'), ('South Taranaki', 'South Taranaki District'), ('Ruapehu', 'Ruapehu District'), ('Rangitikei', 'Rangitikei District'), ('Wanganui', 'Wanganui District'), ('Manawatu', 'Manawatu District'), ('Palmerston North', 'Palmerston North'), ('Tararua', 'Tararua District'), ('Horowhenua', 'Horowhenua District'), ('Masterton', 'Masterton District'), ('Kapiti Coast', 'Kapiti Coast District'), ('Carterton', 'Carterton District'), ('South Wairarapa', 'South Wairarapa District'), ('Upper Hutt', 'Upper Hutt'), ('Porirua', 'Porirua'), ('Hutt', 'Hutt'), ('Wellington', 'Wellington'), ('Tasman', 'Tasman District'), ('Nelson', 'Nelson'), ('Marlborough', 'Marlborough District'), ('Buller', 'Buller District'), ('Grey', 'Grey District'), ('Westland', 'Westland District'), ('Kaikoura', 'Kaikoura District'), ('Hurunui', 'Hurunui District'), ('Selwyn', 'Selwyn District'), ('Waimakariri', 'Waimakariri District'), ('Christchurch', 'Christchurch'), ('Ashburton', 'Ashburton District'), ('Mackenzie', 'Mackenzie District'), ('Timaru', 'Timaru District'), ('Waimate', 'Waimate District'), ('Waitaki', 'Waitaki District'), ('Queenstown-Lakes', 'Queenstown-Lakes District'), ('Central Otago', 'Central Otago District'), ('Dunedin', 'Dunedin'), ('Clutha', 'Clutha District'), ('Southland', 'Southland District'), ('Gore', 'Gore District'), ('Invercargill', 'Invercargill')], default='------', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='contact_name',
            field=models.CharField(default='Person of Contact', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='contact_number',
            field=models.CharField(default='Phone Numbers', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='email',
            field=models.EmailField(default='Valid e-mail of person of contact', max_length=254),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='location',
            field=models.CharField(default='Street Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='region',
            field=models.CharField(choices=[('NZ-NTL', 'Northland'), ('NZ-AUK', 'Auckland'), ('NZ-WKO', 'Waikato'), ('NZ-BOP', 'Bay of Plenty'), ('NZ-GIS', 'Gisborne'), ('NZ-HKB', "Hawke's Bay"), ('NZ-TKI', 'Taranaki'), ('NZ-MWT', 'Manawatu-Wanganui'), ('NZ-WGN', 'Wellington'), ('NZ-TAS', 'Tasman'), ('NZ-NSN', 'Nelson'), ('NZ-MBH', 'Marlborough'), ('NZ-WTC', 'West Coast'), ('NZ-CAN', 'Canterbury'), ('NZ-OTA', 'Otago'), ('NZ-STL', 'Southland')], default='------', max_length=6),
        ),
    ]
