# Generated by Django 5.1.1 on 2024-09-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_supportgroup_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='meeting_date',
            field=models.CharField(default='No Date Specify', help_text="Enter meeting date, frequency, or instructions (e.g., 'Every second Tuesday', 'Monthly', 'Contact for next meeting date')", max_length=255),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='contacts',
            field=models.TextField(help_text='Enter contact names and phone numbers, one per line.'),
        ),
    ]
